language: node_js
node_js:
  - 'lts/*'
addons:
  ssh_known_hosts:
    - 37.139.24.127
branches:
  only:
    - master
env:
  global:
    - ARTIFACT=public.tgz
    - DIST_DIR=public
    - REMOTE_APP_DIR=/var/www/hamburger.cloud
    - REMOTE_USER=travis
    - REMOTE_HOST=37.139.24.127
before_install:
  - openssl aes-256-cbc -K $encrypted_1f9ab55ff724_key -iv $encrypted_1f9ab55ff724_iv
    -in travis.enc -out travis -d
script: npm run dist
before_script:
  - chmod 600 travis && mv travis ~/.ssh/id_rsa
after_script:
  - './deploy.sh'
